// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1744707822);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1744710928);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1744707582);
user_pref("app.update.lastUpdateTime.region-update-timer", 1744710808);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1744710784);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1744707342);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1744707702);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1744707251);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1744707946);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{75f8af9e-55cd-438b-98ec-c27aa82120f2}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1744707191);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3ba07d5c-8ac5-4323-938c-e4e6e25d8af7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1744707193);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1744710784656");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1744712579656");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1744707197991");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1744728797991");
user_pref("browser.search.region", "MA");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1744710780");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230309232128");
user_pref("browser.startup.homepage_override.mstone", "111.0");
user_pref("browser.startup.lastColdStartupCheck", 1744710780);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1744707194685");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "111.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "MA");
user_pref("dom.push.userAgentID", "4234855944444fdea102889600c8e6a8");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1744707822);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230309232128");
user_pref("extensions.lastAppVersion", "111.0");
user_pref("extensions.lastPlatformVersion", "111.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a1fe2dc0-b5f1-417d-9f6d-d5a86b71ec09\",\"pictureinpicture@mozilla.org\":\"a2a67247-004b-4705-b911-6e51ea4881a1\",\"screenshots@mozilla.org\":\"8e71b821-cdb4-4916-88fb-31d9be57bfeb\",\"webcompat-reporter@mozilla.org\":\"6fc2a999-4d7f-44e1-a130-286f418368f6\",\"webcompat@mozilla.org\":\"bb087a44-69f6-4219-be42-7be3c42d3c12\",\"default-theme@mozilla.org\":\"049482fe-5d9c-4be4-ac7c-225aa1593961\",\"addons-search-detection@mozilla.com\":\"2bf97ea4-16e8-47e4-bb4e-6fcee1607ea8\",\"google@search.mozilla.org\":\"950182e4-9cb7-4853-afb6-a79a5d17add6\",\"amazondotcom@search.mozilla.org\":\"2ffee2f3-3651-43cb-81a1-330ea05ddc36\",\"wikipedia@search.mozilla.org\":\"2398fbba-0aa7-4982-9b67-0df1066b608e\",\"bing@search.mozilla.org\":\"f892389f-05df-4e81-bd41-04b73156dd13\",\"ddg@search.mozilla.org\":\"0b4a3f47-d19a-4562-80a3-d2813aae662c\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1744707949);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastDownload", 1744707242);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1744707242);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1744707242);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20230309232128");
user_pref("media.gmp-manager.lastCheck", 1744707242);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1744707949);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1744707949939");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "d60f1686-4878-4818-9fe3-54aafed9c4cd");
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1744710782);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1744710782);
user_pref("services.settings.main.devtools-devices.last_check", 1744710782);
user_pref("services.settings.main.hijack-blocklists.last_check", 1744707701);
user_pref("services.settings.main.language-dictionaries.last_check", 1744710782);
user_pref("services.settings.main.nimbus-desktop-experiments.last_check", 1744710782);
user_pref("services.settings.main.password-recipes.last_check", 1744710782);
user_pref("services.settings.main.sites-classification.last_check", 1744710782);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1744707949);
user_pref("toolkit.startup.last_success", 1744710776);
user_pref("toolkit.telemetry.cachedClientID", "53b7ed33-565b-442e-9e54-b06c8706399a");
user_pref("toolkit.telemetry.previousBuildID", "20230309232128");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
